In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [6]:
#Now create a new Notebook under Jupyter Notebook 

In [7]:
#Similar to the previous lab sheets you need to import the pandas, numpy and matplotlib.pyplot library first. Additionally add the following statement to add the statmodels library which we want to use for regression.

In [3]:
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [5]:
#Import the data from the salary_data.csv file and store it in a data frame. View the content of the data using methods known to you.

In [4]:
dataframe1=pd.read_csv("salary_data.csv")

In [10]:
dataframe1.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [11]:
dataframe1.shape

(30, 2)

In [5]:
#statical discription
dataframe1["YearsExperience"].describe()

count    30.000000
mean      5.313333
std       2.837888
min       1.100000
25%       3.200000
50%       4.700000
75%       7.700000
max      10.500000
Name: YearsExperience, dtype: float64

In [20]:

x=dataframe1.iloc[:,:1].values

In [13]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [17]:
y=dataframe1.iloc[:,1].values

In [15]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872], dtype=int64)

In [18]:

plt.scatter(x,y)

In [21]:
#Fitting the regression model
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [22]:
#resultant regression coefficients using the following commands
print(model.intercept_)
print(model.coef_)


25792.20019866871
[9449.96232146]


In [24]:
#salary for an employee with 5 years of experience
model.predict(np.array([[5]]))

array([73042.01180594])

In [25]:
x1 = sm.add_constant(x)

In [26]:
model = sm.OLS(y,x1).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     622.5
Date:                Wed, 15 Sep 2021   Prob (F-statistic):           1.14e-20
Time:                        11:54:29   Log-Likelihood:                -301.44
No. Observations:                  30   AIC:                             606.9
Df Residuals:                      28   BIC:                             609.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.579e+04   2273.053     11.347      0.000    2.11e+04    3.04e+04
x1          9449.9623    378.755     24.950      0.000    8674.119    1.02e+04
==============================================================================
Omnibus:                        2.140   Durbin-Watson:                   1.648
Prob(Omnibus):                  0.343   Jarque-Bera (JB):                1.569
Skew:                           0.363   Prob(JB):                        0.456
Kurtosis:                       2.147   Cond. No.                         13.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [27]:
#The above statement will add a column of one’s to the data series x. Now use the following statements in the program. They will estimate the regression coefficients for the data using the Ordinary Least Square (OLS) method.